name: foco
description: Um app para ajudar no foco
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^0.13.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.3
  image_picker: ^1.0.4
  provider: ^6.1.2
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - imagem/logo2.png
    - imagem/google.jpg
    - imagem/oii.jpg
    - imagem/likke.png
    - imagem/testees.png
    - imagem/obrigado.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "imagem/testees.png"
